DROP TABLE Shipping_Import_All;
CREATE TABLE Shipping_Import_All (
ORDER_NO varchar(11) NOT null,
CUSTOMER_ID varchar(10) default NULL,
CUSTOMER_PO varchar(15) default NULL,
NAME_CUSTOMER_SHIP varchar(40) default NULL,
ATTENTION varchar(40) default NULL,
ADDRESS_1_SHIP varchar(30) default NULL,
ADDRESS_2_SHIP varchar(30) default NULL,
CITY_SHIP varchar(15) default NULL,
STATE_SHIP char(2) default NULL,
CODE_ZIP_SHIP varchar(13) default NULL,
SHIP_VIA varchar(20) default NULL,
CONTACT_EMAIL varchar(100) default NULL,
SHIP_NOTIFY varchar(5) default NULL,
SHIP_Y char(1) default NULL,
ADDRESS_3_SHIP varchar(30) default NULL,
ADDRESS_4_SHIP varchar(30) default NULL,
ADDRESS_5_SHIP varchar(30) default NULL,
COUNTRY varchar(30) default NULL,
PACKAGES varchar(10) default NULL,
PACKAGE_TYPE varchar(7) default NULL,
WEIGHT double default NULL,
SHIPPING_ACCOUNT varchar(30) default NULL,
WIDTH varchar(50) default NULL,
HEIGHT varchar(50) default NULL,
LENGTH varchar(50) default NULL,
BILLING_OPT varchar(30) default NULL,
CARRIER_OPT char(2) default NULL,
COST varchar(10) default NULL,
PRICE varchar(10) default NULL,
USER_FIELD1H varchar(30) default NULL,
USER_FIELD2H varchar(30) default NULL,
USER_FIELD3H varchar(30) default NULL,
USER_FIELD4H varchar(30) default NULL,
USER_FIELD5H varchar(30) default NULL,
PHONE_NUMBER varchar(15) default NULL,
INT_FLAG bit NOT NULL default 0,
GEN_DESC_GOODS varchar(35) default NULL,
HANDLING_CHRG_OPT char(1) default NULL,
HANDLING_CHRG_TYPE varchar(10) default NULL,
HANDLING_CHRG_PRCNT varchar(6) default NULL,
HANDLING_CHRG_RATE varchar(50) default NULL,
TP_ID varchar(8) default NULL,
TP_NAME varchar(40) default NULL,
TP_ATTENTION varchar(30) default NULL,
TP_ADDRESS1 varchar(40) default NULL,
TP_ADDRESS2 varchar(50) default NULL,
TP_ADDRESS3 varchar(30) default NULL,
TP_ADDRESS5 varchar(30) default NULL,
TP_ADDRESS4 varchar(30) default NULL,
TP_ZIP varchar(12) default NULL,
TP_COUNTRY varchar(20) default NULL,
TP_CITY varchar(35) default NULL,
TP_STATE char(3) default NULL,
TP_ACCOUNT varchar(30) default NULL,
AuxS1 varchar(50) default NULL,
AuxS2 varchar(50) default NULL,
AuxS3 varchar(100) default NULL,
AuxS4 varchar(100) default NULL,
AuxS5 varchar(100) default NULL,
AuxB1 bit NOT NULL default 0,
AuxB2 bit NOT NULL default 0,
AuxN1 double default NULL,
AuxN2 double default NULL,
PACKING_NUMBER varchar(8) default NULL,
CLIENT_NO varchar(4) default NULL,
DATE_STAMP timestamp NOT NULL default now(),
USER_ID varchar(40) default NULL,
F_NAME varchar(60) default NULL,
F_ADD1 varchar(50) default NULL,
F_ADD2 varchar(50) default NULL,
F_CITY varchar(40) default NULL,
F_STATE char(2) default NULL,
F_PHONE varchar(16) default NULL,
F_ZIP varchar(16) default NULL);

DROP TABLE Shipping_Export;
CREATE TABLE Shipping_Export(
ORDER_NO varchar(11) NOT NULL,
VOID_INDICATOR varchar(1) default NULL,
QTY_CARTONS varchar(5) default NULL,
SHIP_WEIGHT varchar(10) default NULL,
SHIP_METHOD varchar(255) default NULL,
PRO_NUMBER varchar(35) default NULL,
COST varchar(50) default NULL,
HANDLINGCHARGE varchar(30) default NULL,
PACKAGE_NUM varchar(50) default NULL,
PICKUP_DATE varchar(34) default NULL,
CUSTOMER_PO varchar(20) default NULL,
REFERENCE1 varchar(50) default NULL,
REFERENCE2 varchar(50) default NULL,
REFERENCE3 varchar(50) default NULL,
REFERENCE4 varchar(50) default NULL,
REFERENCE5 varchar(50) default NULL,
SHIPMENT_ID varchar(37) default NULL,
BILLING_OPT varchar(20) default NULL,
AuxS1 varchar(50) default NULL,
AuxS2 varchar(50) default NULL,
AuxS3 varchar(100) default NULL,
AuxS4 varchar(100) default NULL,
AuxS5 varchar(100) default NULL,
AuxB1 bit NOT NULL default 0,
AuxB2 bit NOT NULL default 0,
AuxN1 double default NULL,
AuxN2 double default NULL,
CLIENT_NO varchar(4) default NULL,
DATE_STAMP timestamp NOT NULL default now(),
USER_ID varchar(30) default NULL,
PROCESS_FLAG bit NOT NULL default 0);